Basic software conf
radxa-docs/docs pull request #117
Opened 2024-05-07 02:30 UTC by nascs

###### Description of changes

2024-05-07 02:53 UTC, RadxaYuntian requested changes

2024-05-07 02:53 UTC, RadxaYuntian commented on docs/common/radxa-os/_basicSoftwareConf.mdx
> +  </tr>
@radxa-docs/editor 之前好像讨论过要不要在文档里面提示rock用户的吧？

2024-05-07 02:53 UTC, RadxaYuntian commented on docs/common/radxa-os/_basicSoftwareConf.mdx
> +同时按下快捷键 "Ctrl" + "Alt" + "T" 唤醒终端，执行以下两条命令更新系统：
别让用户用快捷键，我命令行界面怎么办呢？就说用终端
另外系统更新用rsetup

2024-05-07 03:07 UTC, nascs commented on docs/common/radxa-os/_basicSoftwareConf.mdx
> +同时按下快捷键 "Ctrl" + "Alt" + "T" 唤醒终端，执行以下两条命令更新系统：
行，我修一下 rsetup 的文档

2024-05-07 03:23 UTC, nascs commented on docs/common/radxa-os/_basicSoftwareConf.mdx
> +同时按下快捷键 "Ctrl" + "Alt" + "T" 唤醒终端，执行以下两条命令更新系统：
> 别让用户用快捷键，我命令行界面怎么办呢？就说用终端 另外系统更新用rsetup

要不还是分情况吧，因为小白也可能不知道终端在哪呢

2024-05-07 03:24 UTC, nascs commented on docs/common/radxa-os/_basicSoftwareConf.mdx
> +同时按下快捷键 "Ctrl" + "Alt" + "T" 唤醒终端，执行以下两条命令更新系统：
> > 别让用户用快捷键，我命令行界面怎么办呢？就说用终端 另外系统更新用rsetup
> 
> 要不还是分情况吧，因为小白也可能不知道终端在哪呢

分桌面版和命令行版

2024-05-07 07:42 UTC, nascs commented on i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_basicSoftwareConf.mdx
> +See the <a href={props.system_update_path}> System Update </a> section to update your system.
这里要跳转到 rock5/rock5itx/getting-started/basic-software-conf

2024-05-07 07:52 UTC, nascs commented on i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_basicSoftwareConf.mdx
> +See the <a href={props.system_update_path}> System Update </a> section to update your system.
我感觉 “系统更新” 这里也应该像其他步骤一样在本页面展开具体步骤

2024-05-07 07:54 UTC, nascs commented on i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_basicSoftwareConf.mdx
> +See the <a href={props.system_update_path}> System Update </a> section to update your system.
> 我感觉 “系统更新” 这里也应该像其他步骤一样在本页面展开具体步骤

因为这里定位是基础软件配置

2024-05-07 08:08 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_basicSoftwareConf.mdx
> +See the <a href={props.system_update_path}> System Update </a> section to update your system.
那么现在这个文档的框架就是有问题的

首先你现在这么写了那么其他所有使用到了BasicSoftWareConf的页面都需要传入这个参数才能正常工作，否则href就是空的

其次既然所有页面都需要这个，那应该想一个办法来实现共用而不是每次都要单独配置。要么规定产品的文件结构然后这里硬编码，要么有一个专门的配置文件来存储这个信息。现在这个设计有太多额外的自由度了，反而容易引起滥用

@radxa-docs/editor 看看怎么处理

2024-05-08 09:55 UTC, akgnah approved these changes

2024-05-08 09:55 UTC, merged