fix: zero: repair not correctly line feeds
radxa-docs/docs pull request #135
Opened 2024-05-11 03:28 UTC by CodeChenL

###### Description of changes
* close https://github.com/radxa-docs/docs/issues/119

2024-05-11 03:49 UTC, RadxaYuntian requested changes

2024-05-11 03:49 UTC, RadxaYuntian commented on docs/zero/zero/getting-started/download.md
> +- 因此，引脚 35（GPIOAO_8）没有连接到 40 引脚针座上
这两个是一个更改

2024-05-11 03:49 UTC, RadxaYuntian commented on docs/zero/zero/getting-started/download.md
> +- 引脚 38（GPIOAO_10）现在没有连接到 40 针针座上
这三个是一个更改

2024-05-13 02:55 UTC, CodeChenL commented on docs/zero/zero/getting-started/download.md
> +- 因此，引脚 35（GPIOAO_8）没有连接到 40 引脚针座上
```suggestion
- 电源 LED 现在可由 GPIOAO_8 控制，因此引脚 35（GPIOAO_8）没有连接到 40 引脚针座上
```

2024-05-13 02:55 UTC, CodeChenL commented on docs/zero/zero/getting-started/download.md
> +- 引脚 38（GPIOAO_10）现在没有连接到 40 针针座上
```suggestion
- 电源 LED 现在可由 GPIOAO_10 控制，因此引脚 35（GPIOAO_8）现在连接到了 40 针针座上，引脚 38（GPIOAO_10）现在没有连接到 40 针针座上
```

2024-05-13 03:21 UTC, RadxaYuntian requested changes
英文同步更改后rebase

2024-05-13 06:42 UTC, RadxaYuntian approved these changes

2024-05-13 06:58 UTC, akgnah approved these changes

2024-05-13 06:58 UTC, merged