add Install the Microsoft ODBC driver for SQL Server Docs and resolve some pre-commit checked issues
radxa-docs/docs pull request #150
Opened 2024-05-13 10:02 UTC by CodeChenL

###### Description of changes
* closes #133

2024-05-13 10:37 UTC, u7985 commented on docs/common/apps/_msodbcsql.mdx
> +恢复方法：
这个脚本可能有问题，1. 依赖运行的路径；2. ln 也需要 sudo 权限

2024-05-13 11:44 UTC, RadxaYuntian requested changes

2024-05-13 11:44 UTC, RadxaYuntian commented on docs/common/apps/_msodbcsql.mdx
> +
```suggestion

您在参照上述说明执行安装时可能会遇到以下错误：

```

2024-05-13 11:44 UTC, RadxaYuntian commented on docs/common/apps/_msodbcsql.mdx
> +```
````suggestion
此问题是由于微软所提供的安装包会试图同时在`/usr/lib`以及`/usr/lib64`下安装相关文件，然而 Rockchip 所提供的 Chromium 需要将 `/usr/lib64` 软链接到 `/usr/lib` 下方可正常运行，这导致了 `dpkg` 无法正确进行文件安装。

## 解决方法

请执行以下命令来删除软链接：

```bash
sudo rm /usr/lib64
```

然后可继续从原教程中出错的那步开始重新执行。

:::warning
此操作会导致 Chromium 功能异常，并且无法安全回退。
:::
````

2024-05-13 11:44 UTC, RadxaYuntian commented on docs/common/apps/_msodbcsql.mdx
> +恢复方法：
运行路径倒不是问题，ln命令可以理解成cp，在前的参数是src在后的参数是dest。这里dest是绝对路径，而src是一个相对路径的软链接，最终还是会指向`/usr/lib`。
这个命令的问题在与你这么做了之后odbc的包就被破坏了，并且用户可能有一些其他的包只安装到`/usr/lib64`里面。这个操作本质上执行之后是不能回退的，所以修改意见里面就删掉了。

2024-05-14 09:09 UTC, RadxaYuntian approved these changes

2024-05-14 09:09 UTC, akgnah approved these changes

2024-05-14 09:09 UTC, merged

2024-05-14 09:10 UTC, CodeChenL commented
@akgnah 等等合并，我还要添加英文文档