feat: add creat Wi-Fi AP docs
radxa-docs/docs pull request #183
Opened 2024-05-21 10:32 UTC by CodeChenL

###### Description of changes

2024-05-21 11:04 UTC, RadxaYuntian requested changes

2024-05-21 11:04 UTC, RadxaYuntian commented on docs/common/radxa-os/_ap.mdx
补充一下kde桌面开启ap的说明

2024-05-22 07:05 UTC, RadxaYuntian requested changes

2024-05-22 07:05 UTC, RadxaYuntian commented on docs/common/radxa-os/_ap.mdx
> +<TabItem value="KDE">
KDE放到前面，是默认的选择

2024-05-22 07:05 UTC, RadxaYuntian commented on docs/common/radxa-os/_ap.mdx
> +<TabItem value="Shell">
```suggestion
<TabItem label="命令行" value="Shell">
```

2024-05-22 08:09 UTC, RadxaYuntian requested changes
整理一下提交

2024-05-22 08:12 UTC, CodeChenL commented
> 整理一下提交

还要加英文

2024-05-22 10:20 UTC, RadxaYuntian approved these changes

2024-05-22 10:40 UTC, akgnah approved these changes

2024-05-22 10:40 UTC, merged