feat: add enable RK3588 Mali GPU driver docs
radxa-docs/docs pull request #262
Opened 2024-06-17 09:35 UTC by CodeChenL

###### Description of changes

2024-06-17 09:43 UTC, RadxaYuntian requested changes

2024-06-17 09:43 UTC, RadxaYuntian commented on docs/common/radxa-os/_mali-gpu.mdx
> +sudo apt install libmali-valhall-g610-g13p0-x11-gbm
```suggestion
sudo apt update
sudo apt-get install libmali-valhall-g610-g13p0-x11-gbm
```
教程里涉及到了apt一律使用apt-get，前者的cli不是稳定接口
教程里涉及到了apt安装包一律先apt-get update

2024-06-17 09:43 UTC, RadxaYuntian commented on docs/common/radxa-os/_mali-gpu.mdx
> +Pin-Priority: 1001
```suggestion
Package: *xserver*
Pin: release a=rk3588s2-bookworm
Pin-Priority: 1001

Package: *xorg*
Pin: release a=rk3588s2-bookworm
Pin-Priority: 1001
```
我们还有rk3588s2-bookworm仓库，理论上可能会和rk3588-bookworm里面的内容不同步。这里都加上，但具体用哪个要看用户自己的source了
另外不需要在文档里面支持测试源

2024-06-17 09:43 UTC, RadxaYuntian commented on docs/common/radxa-os/_mali-gpu.mdx
> +```
应该是通过rsetup更新吧，有可能会涉及到downgrade

2024-06-20 04:01 UTC, peterwang2050 approved these changes

2024-06-20 06:20 UTC, RadxaYuntian requested changes

2024-06-20 06:20 UTC, RadxaYuntian commented on docs/common/radxa-os/_mali-gpu.mdx
> +然后参考[使用 Rsetup 进行系统升级](./rsetup#system-update)
```suggestion
然后参考[使用 `rsetup` 进行系统升级](./rsetup#system-update)来重新安装 Rockchip 专有软件包。
```

2024-06-20 06:20 UTC, RadxaYuntian commented on docs/common/radxa-os/_mali-gpu.mdx
> +## 安装用户层驱动
这一步是不是放在下一步的后面，这样可以省去一个apt-get update

2024-06-20 06:55 UTC, RadxaYuntian requested changes

2024-06-20 06:55 UTC, RadxaYuntian commented on docs/common/radxa-os/_mali-gpu.mdx
> +Package: *xserver*
是不是只用xserver-*就可以了？不需要两个entries
![image](https://github.com/radxa-docs/docs/assets/95260730/b0f57597-9d43-4cf1-a161-c5a4635db333)

2024-06-20 10:04 UTC, RadxaYuntian requested changes
新的pin自测一下

2024-06-20 10:04 UTC, RadxaYuntian commented on docs/common/radxa-os/_mali-gpu.mdx
> +
```suggestion
```

2024-06-21 09:46 UTC, CodeChenL commented
> 新的pin自测一下

测过了没问题

2024-06-21 09:46 UTC, CodeChenL commented on docs/common/radxa-os/_mali-gpu.mdx
> +
文件行尾不用留一行吗

2024-06-21 10:10 UTC, RadxaYuntian commented on docs/common/radxa-os/_mali-gpu.mdx
> +
你这就是`Pin-Priority: 1001\n\n`留了两行了啊

2024-06-24 02:35 UTC, CodeChenL commented on docs/common/radxa-os/_mali-gpu.mdx
> +
我这边是一行呀
![image](https://github.com/radxa-docs/docs/assets/43897062/2561877c-6560-4a70-81b5-d6ae9541007e)

2024-06-24 03:40 UTC, RadxaYuntian commented on docs/common/radxa-os/_mali-gpu.mdx
> +
你第二个```上面不是又一个空行么，然后pin-priority那一行本身结尾就是一个换行，所以总共是两个换行

2024-06-24 07:15 UTC, RadxaYuntian requested changes
squash

2024-06-25 01:56 UTC, RadxaYuntian requested changes

2024-06-25 01:56 UTC, RadxaYuntian commented on docs/common/radxa-os/_mali-gpu.mdx
> +Rock 5 系列在 Debian Bookworm 版本默认使用 Panthor GPU 驱动，如需切换到 Mali GPU 驱动，请根据下方教程操作。
```suggestion
ROCK 5 系列在 Debian 12 (Bookworm) 版本默认使用 Panthor GPU 驱动，如需切换到 Mali GPU 驱动，请根据下方教程操作。
```

2024-06-25 01:56 UTC, RadxaYuntian commented on docs/common/radxa-os/_mali-gpu.mdx
> +## 修改 xorg-xserver 默认使用 Rockchip 版本
```suggestion
## 使用 Rockchip 专有 xorg-xserver 版本
```

2024-06-25 01:56 UTC, RadxaYuntian commented on docs/common/radxa-os/_mali-gpu.mdx
> +## 安装用户层驱动
```suggestion
## 安装 Mali 用户层驱动
```

2024-06-25 03:29 UTC, RadxaYuntian approved these changes

2024-06-26 09:43 UTC, peterwang2050 approved these changes

2024-06-26 09:43 UTC, merged

2024-07-05 15:06 UTC, Dark-Existed commented
@CodeChenL 你好 按照步骤操作时候
sudo apt-get install libmali-valhall-g610-g13p0-x11-gbm

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libmali-valhall-g610-g13p0-x11-gbm

找不到这个包

2024-07-05 15:29 UTC, Dark-Existed commented
@CodeChenL 
<img width="586" alt="image" src="https://github.com/radxa-docs/docs/assets/24956657/af55888b-239a-4374-aa54-dce68ccc8bd9">

🤔 目前的源 只有这个 直接重启后 Desktop 起不来了