feat: add ROCK 5C folder structure
radxa-docs/docs pull request #3
Opened 2024-03-26 11:57 UTC by vamrs-feng

###### Description of changes

2024-03-27 08:03 UTC, peterwang2050 requested changes

2024-03-27 08:03 UTC, peterwang2050 commented on docs/rock5/rock5c/accessories/display.md
> +
屏幕的内容是不是功能的，能否import的形式import进来。

2024-03-27 08:03 UTC, peterwang2050 commented on docs/rock5/rock5c/accessories/display.md
> +
添加购买链接

2024-03-27 08:03 UTC, peterwang2050 commented on docs/rock5/rock5c/getting-started/install-os.md
> +
这个你要看下，下载镜像的链接是否正确

2024-03-27 08:09 UTC, vamrs-feng commented on docs/rock5/rock5c/getting-started/install-os.md
> +
现在还没有可用镜像

2024-03-27 08:09 UTC, vamrs-feng commented on docs/rock5/rock5c/accessories/display.md
> +
每个支持的不一样暂时不共用

2024-03-27 08:14 UTC, vamrs-feng commented on docs/rock5/rock5c/README.md
> +# ROCK 5C
标注图暂时没有，其他的要先整理一下。

2024-04-01 12:48 UTC, peterwang2050 commented on docs/rock5/rock5c/getting-started/install-os.md
> +- USB 转 TTL 串口线
这个去掉，这个文档模板是为了让小白都能上手使用，这个小白用不到

2024-04-01 12:49 UTC, peterwang2050 commented on docs/rock5/rock5c/getting-started/install-os.md
> +请到 [ROCK5 官方镜像](../../official-images.md) 下载对应的镜像文件
下载的文件 要放到5C的文档目录下

2024-04-01 12:50 UTC, peterwang2050 commented on docs/rock5/rock5c/getting-started/install-os.md
> +:::
添加 系统登录 项，参考ROCK 5B

2024-04-01 13:09 UTC, peterwang2050 requested changes

2024-04-01 13:09 UTC, peterwang2050 commented on docs/rock5/rock5c/hardware-design/hardware-interface.md
> +## 调试串口
这个放到最后吧，这个尽量不要让用户态关注

2024-04-01 13:09 UTC, peterwang2050 commented on docs/rock5/rock5c/hardware-design/hardware-interface.md
> +
链接到 getting-started的 配件使用中

2024-04-01 13:09 UTC, peterwang2050 commented on docs/rock5/rock5c/hardware-design/hardware-interface.md
> +支持 MIPI 屏幕
链接到 getting-started的 配件使用中

2024-04-01 13:09 UTC, peterwang2050 commented on docs/rock5/rock5c/low-level-dev/install-os-via-usb-otg.md
> +请到 [ROCK 5 官方镜像](../../official-images.md) 下载对应的镜像文件
将 下载地址链接 放到 get-started里面

2024-04-01 13:09 UTC, peterwang2050 commented on docs/rock5/rock5c/getting-started/accessory-usage.md
> +<table>
如果你在配件里面有些支持的型号，这个就不要写，如果这里写了，有点重复

2024-04-02 11:49 UTC, peterwang2050 requested changes

2024-04-03 03:58 UTC, peterwang2050 requested changes

2024-04-03 03:58 UTC, peterwang2050 commented on docs/rock5/rock5c/radxa-os/README.md
> +import Serial from "../../../common/general/\_serial.mdx"
这个引用也可以删掉

2024-04-03 03:58 UTC, peterwang2050 commented on docs/rock5/rock5c/getting-started/install-os.md
> +  - eMMC Module， 大于8GB， 推荐使用 [Radxa eMMC Module](../../../accessories/emmc_module) （用于从 eMMC Module 启动）
把配件引用到5C 文件目录下，后面外部的文件夹会删除

2024-04-03 03:58 UTC, peterwang2050 commented on docs/rock5/rock5c/getting-started/install-os.md
> +  - [eMMC 读卡器](../../../accessories/emmc_reader)（用于从 eMMC Module 启动）.
把配件import进来

2024-04-03 07:03 UTC, peterwang2050 approved these changes

2024-04-03 07:03 UTC, merged