feat: rk3588: add enable Panthor docs
radxa-docs/docs pull request #328
Opened 2024-07-16 05:44 UTC by CodeChenL

###### Description of changes

2024-07-16 05:45 UTC, CodeChenL commented
中文文档没问题后修改英文文档

2024-07-16 06:19 UTC, RadxaYuntian requested changes

2024-07-16 06:19 UTC, RadxaYuntian commented on docs/common/radxa-os/_mali-gpu.mdx
> +添加 `/etc/apt/preferences.d/mali` 文件，内容为：
删除这个文件吧，如果是现有用户我们在升级时默认就升到panthor

2024-07-16 06:19 UTC, RadxaYuntian commented on docs/common/radxa-os/_mali-gpu.mdx
> +sudo apt-get install mesa-utils mesa-utils-extra libglx-mesa0 libgl1-mesa-dri
所有的apt-get install之前都要先update

2024-07-16 06:19 UTC, RadxaYuntian commented on docs/compute-module/cm5/radxa-os/mali-gpu.md
> +# 切换 Mali GPU 驱动
叫`切换 GPU 驱动`就好

2024-07-16 08:01 UTC, RadxaYuntian requested changes
英文加上并squash吧

2024-07-16 08:01 UTC, RadxaYuntian commented
另外cz.toml的改动可以去掉，你squash后提交标题可以重新写的

2024-07-16 08:21 UTC, CodeChenL commented
> 另外cz.toml的改动可以去掉，你squash后提交标题可以重新写的

但是万一别的提交刚好是非第一个单词是update呢，我以前好像就遇到过

2024-07-16 09:02 UTC, RadxaYuntian approved these changes

2024-07-17 12:31 UTC, peterwang2050 approved these changes

2024-07-17 12:31 UTC, merged