fix: modify the naming of the mirror file download and add a description
radxa-docs/docs pull request #378
Opened 2024-08-05 02:38 UTC by lsj123lsjlsj

fix: modify the naming of the mirror file download and add a description

Signed-off-by: SongJun Li <lisongjun@radxa.com>

2024-08-05 03:55 UTC, RadxaYuntian requested changes

2024-08-05 03:55 UTC, RadxaYuntian commented on docs/e/e20c/download.md
> +[rock2-general-2a-2f-e20c_bulleye_xfce_b1.img](https://github.com/radxa-build/rock-2/releases/download/b1/rock-2_bullseye_xfce_b1.output.img.xz)
别装着自己是什么别的文件了，用户不是刚刚才因为这个才发邮件来问为什么下下来的文件名和网页的文件名不符？

2024-08-05 03:56 UTC, RadxaYuntian commented
另外其他2款产品对应的下载页面也检查一下有没有同样的问题

2024-08-05 10:03 UTC, lsj123lsjlsj commented on docs/e/e20c/download.md
> +[rock2-general-2a-2f-e20c_bulleye_xfce_b1.img](https://github.com/radxa-build/rock-2/releases/download/b1/rock-2_bullseye_xfce_b1.output.img.xz)
> 别装着自己是什么别的文件了，用户不是刚刚才因为这个才发邮件来问为什么下下来的文件名和网页的文件名不符？

那网页的文件名就改成和镜像名一样的了？

2024-08-05 10:08 UTC, RadxaYuntian commented on docs/e/e20c/download.md
> +[rock2-general-2a-2f-e20c_bulleye_xfce_b1.img](https://github.com/radxa-build/rock-2/releases/download/b1/rock-2_bullseye_xfce_b1.output.img.xz)
对

2024-08-08 15:59 UTC, peterwang2050 approved these changes

2024-08-08 16:00 UTC, merged