feat: add create Wi-Fi AP and set station mode docs
radxa-docs/docs pull request #383
Opened 2024-08-06 09:18 UTC by lsj123lsjlsj

feat: add create Wi-Fi AP and set station mode docs

Signed-off-by: SongJun Li <lisongjun@radxa.com>

2024-08-06 09:23 UTC, RadxaYuntian reviewed
你这个模块没有文件在引用啊

2024-08-06 09:28 UTC, lsj123lsjlsj commented
> 你这个模块没有文件在引用啊

那我在rock 2那里使用下？

2024-08-07 02:06 UTC, RadxaYuntian requested changes

2024-08-07 02:06 UTC, RadxaYuntian commented on docs/common/radxa-os/_ap-and-sta.mdx
> +sudo iw phy phy0 interface add myAcc type __ap
```suggestion
sudo iw phy phy0 interface add ap0 type __ap
```
用户应该已经有wlan0作为station，只需要添加ap节点就好
后面内容对应改一下

2024-08-07 02:06 UTC, RadxaYuntian commented on docs/common/radxa-os/_ap-and-sta.mdx
> +2.连接 WIFI
```suggestion
2.连接 Wi-Fi
```

2024-08-07 02:06 UTC, RadxaYuntian commented on docs/common/radxa-os/_ap-and-sta.mdx
> +sudo nmcli d w c test-5G password 12345678 ifname mySta
这里的`d w c`尽量用完整的keyword，好理解一些

2024-08-08 16:07 UTC, peterwang2050 approved these changes

2024-08-08 16:23 UTC, peterwang2050 approved these changes

2024-08-08 16:23 UTC, merged