fix: common: optimize SSH related documents
radxa-docs/docs pull request #411
Opened 2024-08-19 08:34 UTC by CodeChenL

* closes https://github.com/radxa-docs/docs/issues/402

###### Description of changes

2024-08-19 08:51 UTC, RadxaYuntian requested changes

2024-08-19 08:51 UTC, RadxaYuntian commented on docs/common/radxa-os/_remote-access.mdx
> +- 如果 Active 为非活动（死机），则 SSH 已停止，即服务未运行，需要重新启动。
这个死机明显是机器翻译吧，看看locale改成中文后是啥

2024-08-19 10:01 UTC, CodeChenL commented on docs/common/radxa-os/_remote-access.mdx
> +- 如果 Active 为非活动（死机），则 SSH 已停止，即服务未运行，需要重新启动。
和英语一样

2024-08-19 10:13 UTC, RadxaYuntian approved these changes

2024-08-23 06:55 UTC, peterwang2050 approved these changes

2024-08-23 06:56 UTC, merged