fix: rename rtsp to hw-codec and update the content
radxa-docs/docs pull request #459
Opened 2024-09-12 05:42 UTC by CodeChenL

###### Description of changes

2024-09-12 08:29 UTC, RadxaYuntian reviewed
别改文件名吧，这样老链接又挂了
我感觉这个还是在说rtsp的问题

2024-09-12 08:29 UTC, RadxaYuntian commented on docs/common/dev/_hw-codec.mdx
> +./ffplay -i rtsp://192.168.10.9:8554/stream
自动硬件解码么？

2024-09-12 08:49 UTC, CodeChenL commented on docs/common/dev/_hw-codec.mdx
> +./ffplay -i rtsp://192.168.10.9:8554/stream
噢，忘记加上硬件解码参数了

2024-09-12 09:12 UTC, RadxaYuntian requested changes

2024-09-12 09:12 UTC, RadxaYuntian commented on docs/common/dev/_rtsp.mdx
> +./ffmpeg -f v4l2 -i /dev/video-camera0 -vf "fps=30" -s 3840x2160 -c:v h264_rkmpp -rc_mode AVBR -b:v 20M -minrate 10M -maxrate 40M -profile:v main -level 5.1 -f rtsp rtsp://0.0.0.0:8554/stream
上面不是make install了么，不需要切换目录吧

2024-09-12 09:12 UTC, RadxaYuntian commented on docs/common/dev/_rtsp.mdx
> +`-vf "fps=30"` 与 `-s 3840x2160` 分别对应帧率与分辨率，需根据命令 `sudo v4l2-ctl -d /dev/video-camera0 --all` 的输出进行调整，否则可能会因为无法自动读取到摄像头信息而影响编码性能甚至启动推流失败。
提供除了`-c:v h264_rkmpp`其他可能的编码选项

2024-09-12 09:12 UTC, RadxaYuntian commented on docs/common/dev/_rtsp.mdx
其他除了`mpph265enc`以外的pipeline

2024-09-12 09:12 UTC, RadxaYuntian commented on docs/common/dev/_rtsp.mdx
> +### 以下以 Windows 下运行 [VLC](https://www.videolan.org/vlc/) 为例，介绍如何收看 RTSP 视频推流。
```suggestion
### <章节名>

以下以 Windows 下运行 [VLC](https://www.videolan.org/vlc/) 为例，介绍如何收看 RTSP 视频推流。
```
不要滥用###章节标签作为加粗格式化的替代。需要分节那添加一个专门的章节名

2024-09-23 08:19 UTC, RadxaYuntian requested changes

2024-09-23 08:19 UTC, RadxaYuntian commented on docs/common/dev/_rtsp.mdx
> +sudo apt-get install build-essential cmake git librockchip-mpp-dev librga-dev libdrm-dev libsdl2*-dev libx264-dev libx265-dev pkg-config
包名字按照字母顺序排序吧。现在这样一眼看不出到底是改了啥

2024-09-23 08:19 UTC, RadxaYuntian commented on docs/common/dev/_rtsp.mdx
> +# gst-launch-1.0 --gst-debug-level=3 v4l2src device=/dev/video-camera0 ! queue ! mpph265enc bps=51200000 rc-mode=vbr ! h265parse ! mp4mux ! filesink location=output.mp4
不是test-launch么？

2024-09-23 08:28 UTC, CodeChenL commented on docs/common/dev/_rtsp.mdx
> +# gst-launch-1.0 --gst-debug-level=3 v4l2src device=/dev/video-camera0 ! queue ! mpph265enc bps=51200000 rc-mode=vbr ! h265parse ! mp4mux ! filesink location=output.mp4
test-launch是rtsp server的启动器，正常录视频用gst-launch-1.0就行

2024-09-23 09:48 UTC, RadxaYuntian requested changes
squash

2024-09-25 06:32 UTC, merged