fix: add system upgrade warning
radxa-docs/docs pull request #46
Opened 2024-04-15 07:03 UTC by CodeChenL

###### Description of changes

2024-04-16 06:30 UTC, RadxaYuntian requested changes

2024-04-16 06:36 UTC, RadxaYuntian requested changes
rebase

2024-04-16 08:16 UTC, peterwang2050 approved these changes

2024-04-16 08:16 UTC, merged

2024-04-26 02:58 UTC, RadxaYuntian commented
https://github.com/radxa-docs/docs/commit/fc25ce6bc83d36bba8931b7574ceb6d4ed0fe01a#diff-10328679cdfd167ffbc9e5acc9a42982e1af3bee991c347b169421a6d61c27d7R77
这里的update应该是upgrade