perf: install os form nvme using SD card/eMMC as a boot disk
radxa-docs/docs pull request #47
Opened 2024-04-15 11:12 UTC by nascs

###### Description of changes

2024-04-15 13:10 UTC, peterwang2050 requested changes

2024-04-15 13:10 UTC, peterwang2050 commented on docs/common/dev/_nvme.mdx
> +## 思路：
整体步骤

2024-04-15 13:10 UTC, peterwang2050 commented on docs/common/dev/_nvme.mdx
> +
eMMC => eMMC Module

2024-04-15 13:10 UTC, peterwang2050 commented on docs/common/dev/_nvme.mdx
> +这里 SD卡/eMMC 的作用相当于 x86 的启动盘，目的是拿到 spi.img， 将 spi.img 刷到 spi flash 中。从 SD 卡/eMMC 启动后，执行一下命令以更新系统:
提示用户：如何制作启动盘， 可以放链接

2024-04-15 13:10 UTC, peterwang2050 commented on docs/common/dev/_nvme.mdx
> +<img
图片过大

2024-04-15 13:10 UTC, peterwang2050 commented on docs/common/dev/_nvme.mdx
> +
将这里分开来写
1. 如何判断系统是否识别NVME
2. 哪里下载景象，如何Copy到启动盘中

2024-04-16 01:18 UTC, nascs commented on docs/common/dev/_nvme.mdx
> +这里 SD卡/eMMC 的作用相当于 x86 的启动盘，目的是拿到 spi.img， 将 spi.img 刷到 spi flash 中。从 SD 卡/eMMC 启动后，执行一下命令以更新系统:
这里是 .mdx 文件，不好放链接吧

2024-04-17 08:26 UTC, merged