Optimize gpu switching documentation
radxa-docs/docs pull request #501
Opened 2024-10-17 11:54 UTC by CodeChenL

###### Description of changes

2024-10-18 02:29 UTC, RadxaYuntian requested changes

2024-10-18 02:29 UTC, RadxaYuntian commented on docs/common/radxa-os/_mali-gpu.mdx
> +2. <font style={{ color: "#ff0000" }}>
仓库里面我记得好像有个给文字着色的组件

2024-10-18 02:29 UTC, RadxaYuntian commented on docs/common/radxa-os/_mali-gpu.mdx
> +Pin: release a=rk3588-bookworm-test
要开头说明支持的soc仅限rk3588和3588s2，现在有3582的5c lite了

2024-10-18 02:29 UTC, RadxaYuntian commented on docs/common/radxa-os/_mali-gpu.mdx
> +运行以下命令，查看当前 `[installed,automatic]` 对应的 xorg-xserver 版本，使用 mali 驱动时，为 `rk3588*-bookworm`，使用 Panthor 驱动时，版本为 `stable*`。
```suggestion
运行以下命令，查看当前 `[installed,automatic]` 对应的 xorg-xserver 来源。使用 mali 驱动时，为 `rk3588*-bookworm`，使用 Panthor 驱动时，为 `stable`。
```

2024-10-18 03:45 UTC, RadxaYuntian commented on docs/common/radxa-os/_mali-gpu.mdx
> +sudo dmesg | grep fb000000.gpu
你这个也会把mali的消息给显示出来。还是lsmod确认吧

2024-10-18 04:01 UTC, CodeChenL commented on docs/common/radxa-os/_mali-gpu.mdx
> +2. <font style={{ color: "#ff0000" }}>
没找到

2024-10-18 05:55 UTC, RadxaYuntian commented on docs/common/radxa-os/_mali-gpu.mdx
> +2. <font style={{ color: "#ff0000" }}>
`<div className='red'>+5.0V</div>`这种，用我们css里面统一定义的颜色

2024-10-18 08:29 UTC, RadxaYuntian requested changes
squash并添加英文版本

2024-10-18 08:54 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_mali-gpu.mdx
> +```bash
github这边格式都标红了，有本地运行确认么？

2024-10-18 08:55 UTC, RadxaYuntian commented
codeowner少了一个

2024-10-18 09:13 UTC, RadxaYuntian approved these changes

2024-10-23 03:45 UTC, CodeChenL commented
@peterwang2050 request a review

2024-10-23 03:47 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_mali-gpu.mdx
> +       perform this step it will crash the desktop or flip the colors.{" "}
{" "}?

2024-10-23 03:47 UTC, RadxaYuntian commented on docs/common/radxa-os/_mali-gpu.mdx
> +     <strong>
可以把两个tag放在同一行
或者文字不要换行/每行有自己的**_**

2024-10-23 05:50 UTC, CodeChenL commented on i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_mali-gpu.mdx
> +       perform this step it will crash the desktop or flip the colors.{" "}
pre-commit自己加的，我编译后发现没啥问题，其他文档也有这个符号

2024-10-23 07:07 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_mali-gpu.mdx
> +     <!-- prettier-ignore -->
好像格式又不对了？

2024-10-23 07:09 UTC, peterwang2050 approved these changes

2024-10-23 07:09 UTC, merged