feat: display: add gdm and bootparam for display configuration methods
radxa-docs/docs pull request #529
Opened 2024-10-28 11:01 UTC by CodeChenL

###### Description of changes

2024-10-29 03:39 UTC, RadxaYuntian requested changes

2024-10-29 03:39 UTC, RadxaYuntian commented on docs/common/radxa-os/_display.mdx
> +根据以上信息，修改 `/var/lib/gdm3/.config/monitors.xml` 文件 `monitorspec` 部分：
看看gdm3有什么配置工具。不应该直接修改/var里面的内容才是

2024-10-29 03:46 UTC, CodeChenL commented on docs/common/radxa-os/_display.mdx
> +根据以上信息，修改 `/var/lib/gdm3/.config/monitors.xml` 文件 `monitorspec` 部分：
我查到的都是用各自GUI/CLI工具， 比如 https://github.com/maxwellainatchi/gnome-randr-rust 生成 ~/.config/monitors.xml，然后复制到gdm的运行配置目录，没有直接面向gdm的
https://wiki.archlinuxcn.org/wiki/GDM#%E8%AE%BE%E7%BD%AE%E9%BB%98%E8%AE%A4%E6%98%BE%E7%A4%BA%E5%99%A8

2024-10-29 03:58 UTC, RadxaYuntian commented on docs/common/radxa-os/_display.mdx
> +根据以上信息，修改 `/var/lib/gdm3/.config/monitors.xml` 文件 `monitorspec` 部分：
至少这个文件能不能通过命令来生成，用户只要复制就好。现在这样除非你把每个属性和输出的值的对应都写清楚我感觉还是会有很多人搞错

2024-10-29 04:01 UTC, CodeChenL commented on docs/common/radxa-os/_display.mdx
> +根据以上信息，修改 `/var/lib/gdm3/.config/monitors.xml` 文件 `monitorspec` 部分：
这些GUI/CLI配置程序都只能在gnome de运行时才能正常配置，而且CLI程序都是没有持久化配置的，那我写一些注释吧

2024-10-29 07:17 UTC, RadxaYuntian commented on docs/common/radxa-os/_display.mdx
> +      <scale>1</scale> #缩放倍数
你这个注释不符合xml语法吧，用户直接复制后可能会报错
`<!-- xxx -->`这种才是xml的注释吧

2024-10-31 03:53 UTC, RadxaYuntian requested changes
英文也更新一下

2024-11-05 12:43 UTC, merged