Fix GPIO table overflow issue by updating div style for GPIO table
radxa-docs/docs pull request #537
Opened 2024-10-29 13:09 UTC by Paschalis

### Summary of Changes
This pull request addresses the issue of the GPIO table not scrolling horizontally on the hardware interface page. The change involves updating the `<div>` that wraps the GPIO table to include a style for overflow.

### Changes Made
- Updated the div from `<div className='gpio_style'>` to `<div className='gpio_style' style={{ overflow: "auto" }}>`.

Closes #536

2024-10-29 14:40 UTC, Paschalis commented
Hi @peterwang2050, I’m having an issue with some failed checks after pushing recent changes to the scrollable-tables branch. I’ve ensured that the local code passed all necessary tests and reset the last two commits, but the checks still show as failed.. Could you provide some guidance on why this might still be failing, or if there’s a particular commit format or additional step I might have missed?

2024-10-30 02:22 UTC, RadxaYuntian commented
There are extra empty line in your changes: https://github.com/radxa-docs/docs/actions/runs/11575838227/job/32223379144?pr=537#step:3:231

Please [install pre-commit](https://pre-commit.com/#installation) and run `pre-commit run --all-files` to fix styling issue locally.

2024-10-30 02:25 UTC, RadxaYuntian requested changes

2024-10-30 02:25 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/zero/zero/hardware-design/hardware-interface.md
If you can't see the action log, then it is the change like this. You now have 2 consecutive empty lines.

2024-10-30 18:31 UTC, Paschalis commented
Thank you, @RadxaYuntian, for your guidance!

2024-10-31 03:20 UTC, RadxaYuntian requested changes
Please also split the other pre-commit fixes to its own commit, and the GPIO table fix in another commit.

2024-10-31 03:20 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/zero/zero/hardware-design/hardware-interface.md
> +<div className='gpio_style' style={{ overflow :"auto"}} >
```suggestion
<div className='gpio_style' style={{ overflow :"auto" }}>
```
Could use an extra space to match.

2024-10-31 03:20 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/zero/zero2pro/hardware-design/hardware-interface.md
> +<div className='gpio_style' style={{ overflow :"auto"}} >
```suggestion
<div className='gpio_style' style={{ overflow :"auto" }}>
```

2024-10-31 03:20 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/hardware-design/hardware-interface.md
> +<div className='gpio_style' style={{ overflow :"auto"}} >
```suggestion
<div className='gpio_style' style={{ overflow :"auto" }}>
```

2024-10-31 11:39 UTC, peterwang2050 approved these changes

2024-11-01 03:25 UTC, RadxaYuntian approved these changes

2024-11-05 12:38 UTC, peterwang2050 approved these changes

2024-11-05 12:38 UTC, merged