feat: add Rockchip Crypto
radxa-docs/docs pull request #555
Opened 2024-11-07 06:10 UTC by RadxaYuntian

###### Description of changes

Add description about Rockchip Crypto and librkcrypto.

2024-11-07 08:54 UTC, peterwang2050 requested changes

2024-11-07 08:54 UTC, peterwang2050 commented on docs/template/sbc/app-development/rk-crypto.md
> +Rockchip Crypto 需要在设备树中使能对应节点。使能成功后，系统会自动加载对应驱动。
这里是不是要简单举例说明下

2024-11-07 09:43 UTC, RadxaYuntian commented on docs/template/sbc/app-development/rk-crypto.md
> +Rockchip Crypto 需要在设备树中使能对应节点。使能成功后，系统会自动加载对应驱动。
这个之后我们会开启的。

2024-11-08 07:13 UTC, peterwang2050 commented on docs/template/sbc/app-development/rk-crypto.md
> +Rockchip Crypto 需要在设备树中使能对应节点。使能成功后，系统会自动加载对应驱动。
我的意思是用户看到这里 他会有困惑，具体是使能哪个节点

2024-11-08 07:25 UTC, RadxaYuntian commented on docs/template/sbc/app-development/rk-crypto.md
> +Rockchip Crypto 需要在设备树中使能对应节点。使能成功后，系统会自动加载对应驱动。
这个文档的受众是开发人员，但他们不需要关心具体节点是该如何开启，这是我们在BSP调试阶段就应该实现的。所以客户只需要知道如何判断功能是否正常即可，若没有正常开启，应该通知我们的技术支持来修复这个问题。

2024-11-08 08:44 UTC, peterwang2050 approved these changes

2024-11-08 08:44 UTC, merged