feat: common: dev: add _rk_anti_copy_board.mdx
radxa-docs/docs pull request #565
Opened 2024-11-13 10:18 UTC by CodeChenL

###### Description of changes

2024-11-13 10:57 UTC, RadxaYuntian requested changes

2024-11-13 10:57 UTC, RadxaYuntian commented on docs/common/dev/_rk_anti_copy_board.mdx
> +[ Rockchip Anti Copy Board 开发指南](https://gitlab.com/rockchip_linux_sdk_6.1/linux/bsp/docs/-/raw/cn/Common/SECURITY/Rockchip_Developer_Guide_Anti_Copy_Board_CN.pdf?inline=false)
```suggestion
[Rockchip Anti Copy Board 开发指南](https://gitlab.com/rockchip_linux_sdk_6.1/linux/bsp/docs/-/raw/cn/Common/SECURITY/Rockchip_Developer_Guide_Anti_Copy_Board_CN.pdf?inline=false)
```

2024-11-13 10:57 UTC, RadxaYuntian commented on docs/common/dev/_rk_anti_copy_board.mdx
> +中级方案和高级方案则依赖开启 BL32 以运行 optee 来读写 otp 数据，可根据以下章节[开启 BL32 ](#开启-bl32)后继续参考 Rockchip Anti Copy Board 开发指南进行防抄板应用开发。
```suggestion
中级方案和高级方案则依赖开启 BL32 以运行 optee 来读写 otp 数据，可根据以下章节[开启 BL32](#开启-bl32) 后继续参考 Rockchip Anti Copy Board 开发指南进行防抄板应用开发。
```

2024-11-13 10:57 UTC, RadxaYuntian commented on docs/common/dev/_rk_anti_copy_board.mdx
> +每颗芯片的 otp 分区仅可读写一次，请谨慎操作，本文档造成的一切后果概不负责。
```suggestion
每颗芯片的 OTP 存储仅可写入一次，请谨慎操作。瑞莎不对因用户失误所产生的后果负责。
```
后面那个免责条款感觉还要再看看怎么写，毕竟你现在就是在指导用户做这个。要想一下怎么说

2024-11-13 10:57 UTC, RadxaYuntian commented on docs/common/dev/_rk_anti_copy_board.mdx
> +按照[ U-boot 开发](./u-boot)编译打包一次 Bootloader。
```suggestion
按照 [U-boot 开发](./u-boot)编译打包一次 Bootloader。
```

2024-11-13 10:57 UTC, RadxaYuntian commented on docs/common/dev/_rk_anti_copy_board.mdx
> +[0 ~/Documents/GitHub/bsp]$ ./bsp u-boot rknext
我最恨的就是这种不能一次性复制多行命令一次执行的文档

2024-11-13 10:57 UTC, RadxaYuntian commented on docs/common/dev/_rk_anti_copy_board.mdx
> +按照[ U-boot 开发](./u-boot)将 `deb` 包复制至板端并使用 `setup.sh` 刷写 Bootloader。
首尾空格不要包含到链接里面，不再说了

2024-11-13 10:57 UTC, RadxaYuntian commented on docs/common/dev/_rk_anti_copy_board.mdx
> +`BoardProofTool`: [BoardProofTool_v1.01_20240823_02.zip](https://dl.radxa.com/tools/windows/BoardProofTool_v1.01_20240823_02.zip)
这些在tools仓库里面应该有吧，你翻翻我们本地的sdk
如果需要更新我们gitlab的仓库告诉我

2024-11-13 10:57 UTC, RadxaYuntian commented on docs/common/dev/_rk_anti_copy_board.mdx
> +git clone https://gitlab.com/rockchip_linux_sdk_6.1/android/rk/platform/system/rk_tee_user.git -b develop-next
这个有更新么

2024-11-14 01:43 UTC, CodeChenL commented on docs/common/dev/_rk_anti_copy_board.mdx
> +git clone https://gitlab.com/rockchip_linux_sdk_6.1/android/rk/platform/system/rk_tee_user.git -b develop-next
更新了

2024-11-14 01:45 UTC, CodeChenL commented on docs/common/dev/_rk_anti_copy_board.mdx
> +其中初级方案可直接参照 Rockchip 官方文档
```suggestion
其中初级方案可直接参照 Rockchip 官方文档 
```
这是同一行

2024-11-14 01:46 UTC, CodeChenL commented on docs/common/dev/_rk_anti_copy_board.mdx
> +按照[ U-boot 开发](./u-boot)将 `deb` 包复制至板端并使用 `setup.sh` 刷写 Bootloader。
```suggestion
按照 [U-boot 开发](./u-boot)将 `deb` 包复制至板端并使用 `setup.sh` 刷写 Bootloader。
```

2024-11-14 03:28 UTC, CodeChenL commented on docs/common/dev/_rk_anti_copy_board.mdx
> +`BoardProofTool`: [BoardProofTool_v1.01_20240823_02.zip](https://dl.radxa.com/tools/windows/BoardProofTool_v1.01_20240823_02.zip)
已测试内部sdk的tools版本不够新

2024-11-14 05:57 UTC, RadxaYuntian requested changes

2024-11-14 05:57 UTC, RadxaYuntian commented on docs/common/dev/_rk_anti_copy_board.mdx
> +**1. 使用初级方案时读写数据报错？**
直接用###吧，这样客户遇到问题也可以直接发给他对应的解决方案链接

2024-11-14 08:04 UTC, RadxaYuntian commented on docs/common/dev/_rk_anti_copy_board.mdx
> +### 4. Rockchip 官方文档提到的 `BoardProofTool`、`ProofDll` 源码和 `rk_tee_user` 如何获取？
用header就不必编号了吧

2024-11-15 01:49 UTC, RadxaYuntian requested changes
squash后补充一下英文版本

2024-11-15 08:44 UTC, RadxaYuntian approved these changes

2024-11-18 12:01 UTC, peterwang2050 approved these changes

2024-11-18 12:02 UTC, merged