perf: rtsp: replace gst-rtsp-server with mediamtx
radxa-docs/docs pull request #577
Opened 2024-11-20 02:45 UTC by CodeChenL

###### Description of changes

2024-11-20 02:56 UTC, RadxaYuntian reviewed
所以为什么gst-rtsp-server不能用了呢？

2024-11-20 03:49 UTC, CodeChenL commented
> 所以为什么gst-rtsp-server不能用了呢？

很久没人维护这个库了，导致debian更新gst版本后，它的编译脚本找不到gstreamer-rtsp的位置了

2024-11-20 06:32 UTC, RadxaYuntian commented
你现在用的版本也不是最新的呀，最新的gst-rtsp-server也有同样的问题么？

2024-11-20 10:35 UTC, CodeChenL commented
> 你现在用的版本也不是最新的呀，最新的gst-rtsp-server也有同样的问题么？

试过github上的最新代码不行，刚刚发现gitlab上有更新https://gitlab.freedesktop.org/gstreamer/gstreamer/-/tree/main/subprojects/gst-rtsp-server

2024-11-20 10:37 UTC, RadxaYuntian commented
如果gitlab上的可以用的话可以两个都保留，直到rtsp-server不能用为止

2024-11-21 05:44 UTC, CodeChenL commented
meson给的信息太少了，自己写了个cmake导入gst，报错找不到librga。
发现是因为rkr4的gst版本高于debian源的gst，优先安装sdk的gst。
然后sdk的gst的pkgconfig文件相比debian多了librga，所以导致为什么以前可以找到gst-rtsp依赖现在不行。
通过安装librga-dev解决，而且比以前的推流效果好很多。

2024-11-21 06:07 UTC, CodeChenL commented
先提中文

2024-11-21 07:55 UTC, RadxaYuntian requested changes

2024-11-21 08:01 UTC, CodeChenL commented on docs/common/dev/_rtsp.mdx
> +# 查询系统内 gstreamer-rtsp-1.0 的版本号
我们系统默认装了，我加一个

2024-11-21 08:09 UTC, CodeChenL commented on docs/common/dev/_rtsp.mdx
> +# 查询系统内 gstreamer-rtsp-1.0 的版本号
不用加了是`libgstreamer-plugins-base1.0-dev`提供的
```
rock@rock-5b:~/rtw8852be/gstreamer/subprojects/gst-rtsp-server/build$ dpkg -S /usr/lib/aarch64-linux-gnu/libgstrtsp-1.0.so
libgstreamer-plugins-base1.0-dev: /usr/lib/aarch64-linux-gnu/libgstrtsp-1.0.so
rock@rock-5b:~/rtw8852be/gstreamer/subprojects/gst-rtsp-server/build$ dpkg -S /usr/lib/aarch64-linux-gnu/pkgconfig/gstreamer-rtsp-1.0.pc
libgstreamer-plugins-base1.0-dev: /usr/lib/aarch64-linux-gnu/pkgconfig/gstreamer-rtsp-1.0.pc
rock@rock-5b:~/rtw8852be/gstreamer/subprojects/gst-rtsp-server/build$ 
```

2024-11-21 09:09 UTC, RadxaYuntian commented on docs/common/dev/_rtsp.mdx
> +sudo apt-get install gstreamer1.0-rtsp
那为什么这里要安装呢？

2024-11-21 09:30 UTC, CodeChenL commented on docs/common/dev/_rtsp.mdx
> +sudo apt-get install gstreamer1.0-rtsp
因为下面的pipline里的`rtspclientsink`是gstreamer1.0-rtsp，但是gst-rtsp-server方案不依赖这个元素

2024-11-21 09:32 UTC, RadxaYuntian requested changes
整理一下提交

2024-11-21 12:49 UTC, peterwang2050 approved these changes

2024-11-21 12:51 UTC, peterwang2050 approved these changes

2024-11-23 05:29 UTC, peterwang2050 approved these changes

2024-11-23 05:29 UTC, merged