fix: add Q&A for Wireless card
radxa-docs/docs pull request #581
Opened 2024-11-21 07:14 UTC by CodeChenL

###### Description of changes

2024-11-21 07:47 UTC, RadxaYuntian requested changes

2024-11-21 07:47 UTC, RadxaYuntian commented on docs/common/radxa-os/_ap.mdx
> +尝试指定 `Channel` 参数为 `<A (5 GHz)> 36`
这个目前是仅限于A8还是别的wifi也有这个问题？另外我觉得不管怎样，A8还是要保留一个链接过来。用户都按照你上面说的开了两个设备了，很大概率是想要开热点

2024-11-21 08:11 UTC, CodeChenL commented on docs/common/radxa-os/_ap.mdx
> +尝试指定 `Channel` 参数为 `<A (5 GHz)> 36`
一般都是默认开`2.4G`，我给a8链一个

2024-11-21 09:11 UTC, RadxaYuntian requested changes
添加英文后squash吧

2024-11-21 12:45 UTC, peterwang2050 commented on docs/accessories/wireless-a8.md
> +
你这里的表述 没有明显的表示出你要做什么，你这里是要更换rtw89 为 8852be，因为8852be有更多特性，这些特性能否列个一二呢

2024-11-22 03:29 UTC, RadxaYuntian commented on docs/accessories/wireless-a8.md
> +
我觉得都没必要去介绍两个的区别，只需要告诉用户是驱动变更引起的就好了。我们用rtw89的原因只是这是上游内核所使用的驱动，跟别的都没关系

2024-11-22 03:39 UTC, CodeChenL commented on docs/accessories/wireless-a8.md
> +
感觉标题已经说清楚要干什么了？我们也不知道除了`两个 wlan 设备`外的其他特性

2024-11-22 10:54 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/accessories/wireless-a8.md
> +[Trying to specify a channel](../template/sbc/radxa-os/ap#Q&A)
这个&在URL里面能正常工作么？

2024-11-23 05:27 UTC, peterwang2050 approved these changes

2024-11-23 05:27 UTC, merged