fix: change to use rsetup for automatic login configuration
radxa-docs/docs pull request #615
Opened 2024-12-16 09:53 UTC by CodeChenL

###### Description of changes

2024-12-17 08:04 UTC, RadxaYuntian requested changes
英文，同时检查一下图片是否还有其他页面引用。我们应该有个CI检查未引用的图片的

2024-12-19 03:08 UTC, CodeChenL commented
> 英文，同时检查一下图片是否还有其他页面引用。我们应该有个CI检查未引用的图片的

用vscode全局搜索文件名没找到那里还有引用，ci也没报错

2024-12-19 05:47 UTC, RadxaYuntian commented
CI被删了：https://github.com/radxa-docs/documentation/commit/3f0f386cdea98df4ead932003e59017148289665

2024-12-19 05:51 UTC, RadxaYuntian commented
> 用vscode全局搜索文件名没找到那里还有引用，ci也没报错

没有引用就把图片删了吧

2024-12-19 06:11 UTC, CodeChenL commented
@RadxaYuntian request a review

2024-12-19 06:26 UTC, RadxaYuntian approved these changes

2025-01-15 13:26 UTC, closed without merging

2025-01-15 13:26 UTC, peterwang2050 commented
已在其他地方修改过