feat: common: dev: add moonlight
radxa-docs/docs pull request #616
Opened 2024-12-17 08:20 UTC by CodeChenL

###### Description of changes

2024-12-19 05:50 UTC, RadxaYuntian requested changes

2024-12-19 05:50 UTC, RadxaYuntian commented on docs/common/dev/_moonlight.mdx
> +本文思路方法由[@woiza](https://github.com/woiza)提供，在此非常感谢！！！
```suggestion
- [原始使用问题](issue的地址)
```

2024-12-19 06:01 UTC, CodeChenL commented on docs/common/dev/_moonlight.mdx
> +本文思路方法由[@woiza](https://github.com/woiza)提供，在此非常感谢！！！
```suggestion
- [radxa-build/rock-5b Moonlight-qt Rock 5B](https://github.com/radxa-build/rock-5b/issues/26)
```

2024-12-19 06:04 UTC, RadxaYuntian requested changes

2024-12-19 06:04 UTC, RadxaYuntian commented on docs/common/dev/_moonlight.mdx
> +- [radxa-build/rock-5b Moonlight-qt Rock 5B](https://github.com/radxa-build/rock-5b/issues/26)
```suggestion
- [原始用户问题及编译方法](https://github.com/radxa-build/rock-5b/issues/26#issuecomment-2539197643)
```
还是要明显说明出处

2024-12-19 06:27 UTC, RadxaYuntian requested changes
添加英文然后squash吧

2024-12-30 12:57 UTC, peterwang2050 commented on docs/common/dev/_moonlight.mdx
> +参考 [RTSP 推流](../rtsp?target=ffmpeg)，无需参考全部文档，
链接无效

2024-12-30 12:57 UTC, peterwang2050 commented on docs/common/dev/_moonlight.mdx
> +参考至[编译并安装 ffmpeg-rockchip](../rtsp?target=ffmpeg#编译并安装-ffmpeg-rockchip)
链接无效

2024-12-31 09:51 UTC, RadxaYuntian approved these changes

2025-01-08 08:04 UTC, peterwang2050 approved these changes

2025-01-08 08:04 UTC, merged