fix: delete rock-3a wifi
radxa-docs/docs pull request #618
Opened 2024-12-24 07:58 UTC by nascs

###### Description of changes

2024-12-24 08:00 UTC, RadxaYuntian commented on docs/rock3/rock3a/README.md
>      <tr>
是不是说M.2 E key之类的？具体是什么key你自己查一下

2024-12-24 08:14 UTC, nascs commented on docs/rock3/rock3a/README.md
>      <tr>
有 E Key, 支持 A8

2024-12-24 09:09 UTC, RadxaYuntian requested changes

2024-12-24 09:09 UTC, RadxaYuntian commented on docs/rock3/rock3a/README.md
> +        <td align="center"> 支持 Radxa Wireless Module A8(Wi-Fi 6 & BT 5.2)</td>
```suggestion
        <td align="center">M.2 E Key 支持外接 Radxa Wireless Module A8(Wi-Fi 6 & BT 5.2)</td>
```

2024-12-24 09:09 UTC, RadxaYuntian commented on docs/rock3/rock3a/getting-started/preparation.md
> +ROCK 3A 有以太网口，可以通过以太网接入网络， 有 PCIe E Key， 可以通过 Wi-Fi 接入网络。
```suggestion
ROCK 3A 拥有千兆以太网接口以及 M.2 E Key 接口，支持外接 Wi-Fi 网卡。
```
之前太口语化了。另外全角符号后面不用接空格

2024-12-30 12:28 UTC, peterwang2050 approved these changes

2024-12-30 12:29 UTC, merged