Docs itx
radxa-docs/docs pull request #98
Opened 2024-04-28 11:53 UTC by nascs

###### Description of changes

2024-04-28 11:57 UTC, RadxaYuntian requested changes

2024-04-28 11:57 UTC, RadxaYuntian commented on docs/common/dev/_kernel.mdx
> +    -r 20                 # 指定内核的版本号为 20
```suggestion
    -r 20                 # 指定内核的修订号为 20
```
英文为revision number
另外我们现在有的内核的修订号都3x了，你要想优先使用这个内核不如直接设置成999

2024-04-29 02:52 UTC, u7985 commented on docs/rock5/rock5itx/README.md
`2 个 2.5 千兆以太网端口`

`2.5 千兆` 这个说法好像不常用，改 2.5G

2024-04-29 02:55 UTC, u7985 commented on docs/Home.md
`products_name: "ROCK 5ITX"`

产品名字是 `ROCK 5 ITX`

2024-04-29 03:10 UTC, u7985 commented on docs/common/dev/_kernel.mdx
`将上面两个 `deb` 包复制到板子上使用 `dpkg` 指令安装即可完成内核安装`，
`重启完成后可以通过 `uname -a` 查看当前启动的内核版本号来查看是否安装成功`

这两个长句，加标点换成短句，增加可读性，如

`重启完成后，可以通过 `uname -a` 查看当前启动的内核版本，来查看新内核是否安装成功`

2024-04-29 03:14 UTC, u7985 commented on docs/common/radxa-os/_network.mdx
`使用有线上网时，请将网线插入RJ45接口。 桌面右下角会有一个网络连接图标，选择你要连接的网络，输入密码就可以上网了。`

有线网络应该不用输入密码，这个可能是之前遗留的错误

2024-04-29 03:57 UTC, u7985 commented on docs/rock5/rock5itx/getting-started/accessory-usage.md
产品名字是 `ROCK 5 ITX`，这个页面有几个地方要修改

2024-04-29 09:05 UTC, merged